[package]
name = "ancestors-tui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.25.0"
env_logger = "0.9.3"
eyre = "0.6.8"
log = "0.4.17"
tui = "0.19.0"
