[package]
name = "ancestors-tui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.9.3"
eyre = "0.6.8"
log = "0.4.17"
rustyline = "10.0.0"
