[workspace]
resolver = "2"
members = [
  "ancestors-core",
  "ancestors-infra-json",
  "ancestors-kernel",
  "tui",
  "repl",
]

[workspace.dependencies]
gedcomx-model = { git = "https://github.com/kod-kristoff/gedcomx-rust" }
serde = { version = "1" }
