[workspace]
resolver = "2"
members = [
  "ancestors-core",
  "ancestors-infra-json",
  "ancestors-main",
  "ancestors-r3bl",
  "ancestors-realm",
  "ancemad-ui",
  "gui",
  "tui",
  "repl",
  "libs/*",
]
