[package]
name = "gen-services"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
doctest = false

[dependencies]
# external deps
hashbrown.workspace = true

# local deps
gen-types.workspace = true
