xflags::xflags! {
    src "./src/cli/flags.rs"

    cmd ancestors-cli {
        /// Verbosity level.
        optional -v, --verbose
        /// Verbosity level.
        optional --trace
        /// Verbosity level.
        optional -q, --quiet

        cmd scrape {
            required url: String
        }

    }
}
// generated start
// The following code is generated by `xflags` macro.
// Run `env UPDATE_XFLAGS=1 cargo build` to regenerate.
#[derive(Debug)]
pub struct AncestorsCli {
    pub verbose: bool,
    pub trace: bool,
    pub quiet: bool,
    pub subcommand: AncestorsCliCmd,
}

#[derive(Debug)]
pub enum AncestorsCliCmd {
    Scrape(Scrape),
}

#[derive(Debug)]
pub struct Scrape {
    pub url: String,
}

impl AncestorsCli {
    #[allow(dead_code)]
    pub fn from_env_or_exit() -> Self {
        Self::from_env_or_exit_()
    }

    #[allow(dead_code)]
    pub fn from_env() -> xflags::Result<Self> {
        Self::from_env_()
    }

    #[allow(dead_code)]
    pub fn from_vec(args: Vec<std::ffi::OsString>) -> xflags::Result<Self> {
        Self::from_vec_(args)
    }
}
// generated end
