[package]
name = "repl"
version = "0.1.0"
edition = "2021"

[dependencies]
ancestors = { version = "0.1.0", path = "../libs/ancestors" }
clap = { version = "4.1.4", features = ["cargo"] }
env_logger = "0.10.0"
eyre = "0.6.8"
log = "0.4.17"
rustyline = "10.1.1"
serde_json = "1.0.93"
shlex = "1.1.0"
