[package]
name = "ancemad-ui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crokey = "0.4.3"
eyre = "0.6.8"
termimad = "0.23.0"
terminal-clipboard = "0.4.0"
